######################################################################
# Automatically generated by qmake (3.0) ?? ??? 22 14:56:23 2014
######################################################################

TEMPLATE = app
TARGET = calcCore
INCLUDEPATH += .

# Input
HEADERS += include/auxCalcCore.h \
           include/auxMayBe.h \
           include/auxTemplate.h \
           include/calcCore.h \
           include/threadpool.h
SOURCES += src/auxCalcCore.cpp src/calcCore.cpp
