######################################################################
# Automatically generated by qmake (3.0) ?? ??? 22 15:47:43 2014
######################################################################

TEMPLATE = app
TARGET = _testProj
INCLUDEPATH += .

# Input
HEADERS += include/auxDlg.h include/auxQt.h include/tstDlg.h
FORMS += UI/tstDlg.ui
SOURCES += main.cpp src/auxDlg.cpp src/auxQt.cpp src/tstDlg.cpp
